### ISSUE TITLE
Equal Earth - can't create WKT1 string - part 2

### ISSUE THREAD

**Issue by kyngchaos** [OSGeo/proj.4#2862] opened 2021-09-21 01:18 UTC
Continuation of bug: https://github.com/OSGeo/PROJ/issues/2610

While it now works for shapefiles, it still doesn't work for rasters.  From gdalwarp I get:

> ERROR 1: PROJ: proj_as_wkt: Unsupported conversion method: Equal Earth
> ERROR 1: OGRProjCT::Initialize(): if source and/or target CRS are null, a coordinate operation must be specified

And the source raster data is copied in its original projection.  But, the new raster does have the Equal Earth projection definition.  It seems that for one part (adding the projection definition to the raster) GDAL uses a method known to work for eqearth, but for the critical part it uses a method that does not know eqearth (ie WKT1:GDAL).

- PROJ 7.2

**Comment by rouault** [comment] 2021-09-21 08:50
This has been fixed in GDAL 3.3.2 . This is a duplicate of https://github.com/OSGeo/gdal/issues/4133

**Closed as completed by rouault** 2021-09-21 08:50 UTC
Labels: bug
