### ISSUE TITLE
Accuracy problem with helmert transformation 

### ISSUE THREAD

**Issue by sgamperl** [OSGeo/proj.4#3174] opened 2022-04-22 12:58 UTC
Hello,

we identified a problem with the current version of PROJ. We want to transform coordinates from ETRS89 (EPSG:4258) to the austrian coordinate system EPSG:31251 with a custom 7 parameter transformation.

For EPSG:31251 we use the following proj-String: _+proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +towgs84=1243.664,422.935,241.661,16.0070831140,-18.7400563071,3.2832620357,-48.8214 +pm=ferro +units=m +no_defs_

Test:
ETRS89 coordinates: (11.702111000658,47.333295771703,592.292)
Expected destination coordintes: (103478.022, 244736.817, 543.64)

But the result was (103478.018231, 244736.975269, 543.691400)

====================================================================================

We debugged the PROJ-code and found problematic code lines in helmert_reverse_3d in helmert.cpp.

```c
static PJ_LPZ helmert_reverse_3d (...) {

    struct pj_opaque_helmert *Q = (struct pj_opaque_helmert *) P->opaque;
    PJ_COORD point = {{0,0,0,0}};
    double X, Y, Z, scale;
    point.xyz = xyz;

    if (Q->fourparam) {
        const auto lp = helmert_reverse(point.xy, P);
        point.lp = lp;
        return point.lpz;
    }

    if (Q->no_rotation && Q->scale == 0) {
        point.xyz.x  =  xyz.x - Q->xyz.x;
        point.xyz.y  =  xyz.y - Q->xyz.y;
        point.xyz.z  =  xyz.z - Q->xyz.z;
        return point.lpz;
    }

    scale = 1 + Q->scale * 1e-6;

    /* Unscale and deoffset */
    X = (xyz.x - Q->xyz.x) / scale;
    Y = (xyz.y - Q->xyz.y) / scale;
    Z = (xyz.z - Q->xyz.z) / scale;

    /* Inverse rotation through transpose multiplication */
    point.xyz.x  =  ( R00 * X   +   R10 * Y   +   R20 * Z) + Q->refp.x;
    point.xyz.y  =  ( R01 * X   +   R11 * Y   +   R21 * Z) + Q->refp.y;
    point.xyz.z  =  ( R02 * X   +   R12 * Y   +   R22 * Z) + Q->refp.z;

    return point.lpz;
}
```

In the part "Unscale and deoffset" the translation is considered and than the scale is applied. In the official helmert formula the translation is applied without scale - see https://de.wikipedia.org/wiki/Helmert-Transformation.

We did a code research and we found that this code lines (formerly in pj_geocentic_from_wgs84) was changed in 2002 - https://github.com/OSGeo/PROJ/commit/f8e9a822d7e9166b9925f75ba36bb7aa75afc3c1

We didn't find the bug-ticket by the given link http://bugzilla.remotesensing.org/show_bug.cgi?id=194
Can you share the bug ticket to understand the code change?

We only get correct results (which are then equal to results from Leica and rmDATA software) if we change the calculation in this way:

```c
/* take the coordinates without translation*/
X = xyz.x;
Y = xyz.y;
Z = xyz.z;

/* Inverse rotation through transpose multiplication */
// apply the scale to the transformation matrix and than consider translation without the scale
point.xyz.x = (R00 * X + R10 * Y + R20 * Z) / scale + Q->refp.x - Q->xyz.x;
point.xyz.y = (R01 * X + R11 * Y + R21 * Z) / scale + Q->refp.y - Q->xyz.y;
point.xyz.z = (R02 * X + R12 * Y + R22 * Z) / scale + Q->refp.z - Q->xyz.z;
```

**Comment by rouault** [comment] 2022-04-22 16:01
I could reproduce the result you get by doing:

$ echo "11.702111000658 47.333295771703 592.292" |  cct +proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +towgs84=1243.664,422.935,241.661,16.0070831140,-18.7400563071,3.2832620357,-48.8214 +pm=ferro +units=m +no_defs
  103478.0182    244736.9753      543.6914        0.0000

When using this legacy +towgs84 syntax, this is mapped to +proj=helmert +exact (see https://proj.org/operations/transformations/helmert.html).

This is equivalent to using the following pipeline with cct:
$ echo "11.702111000658 47.333295771703 592.292" |  cct -d 4 +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad  +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=1243.664 +y=422.935 +z=241.661 +rx=16.007083114 +ry=-18.7400563071 +rz=3.2832620357 +s=-48.8214 +convention=position_vector +exact +step +inv +proj=cart +ellps=bessel  +step +proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro
  103478.0182    244736.9753      543.6913           inf

If removing the +exact term in it, so using small angle approximation, then you get:
$ echo "11.702111000658 47.333295771703 592.292" |  cct -d 4 +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad  +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=1243.664 +y=422.935 +z=241.661 +rx=16.007083114 +ry=-18.7400563071 +rz=3.2832620357 +s=-48.8214 +convention=position_vector +step +inv +proj=cart +ellps=bessel  +step +proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro
  103478.0237    244736.9832      543.7295           inf

With your suggested formulas, it is similar to actually use the forward computation in the reverse computation, but inverting the signs of the parameters. Which I tried with:

$ echo "11.702111000658 47.333295771703 592.292" |  cct -d 4 +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad  +step +proj=cart +ellps=WGS84 +step +proj=helmert +x=-1243.664 +y=-422.935 +z=-241.661 +rx=-16.007083114 +ry=18.7400563071 +rz=-3.2832620357 +s=48.8214 +convention=position_vector  +step +inv +proj=cart +ellps=bessel  +step +proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro
  103478.0275    244736.8252      543.6778           inf

or with its +exact variant:

$ echo "11.702111000658 47.333295771703 592.292" |  cct -d 4 +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad  +step +proj=cart +ellps=WGS84 +step +proj=helmert +x=-1243.664 +y=-422.935 +z=-241.661 +rx=-16.007083114 +ry=18.7400563071 +rz=-3.2832620357 +s=48.8214 +convention=position_vector +exact +step +inv +proj=cart +ellps=bessel  +step +proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro
  103477.9992    244736.8227      543.6397           inf

None of this gives the value you expect

@busstoptaktik  https://www.iogp.org/wp-content/uploads/2019/09/373-07-02.pdf page 109 mentions doing reversibility of Helmert by using the foward path with opposite sign of the arguments, whereas we use an "exact" inverse (exact is confusing here as it doesn't mean +exact) as far as I can see, right ? ("The EPSG Dataset documents reversibility using the approximation, that is using the same formula as
for the forward calculation but with the signs of the parameter values changed. The alternative of using the
exact reverse formula should be treated as a different method in which the reverse uses a different formula
from the forward calculation and in this the signs of the parameter values are not changed.")

I suspect the result you expect is a mix between the exact inverse method that PROJ uses and the approximation that EPSG would recommend. I suspected the difference might lie in the 1 - s ~= 1 / (1 +s ) approximation being applied or not, but trying with s=48.82824 ( because 1 / (1 -  48.8214e-6) = 1.0000488237836453 ) doesn't improve things much:

$ echo "11.702111000658 47.333295771703 592.292" |  bin/cct -d 4 +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad  +step +proj=cart +ellps=WGS84 +step +proj=helmert +x=-1243.664 +y=-422.935 +z=-241.661 +rx=-16.007083114 +ry=18.7400563071 +rz=-3.2832620357 +s=48.82824 +convention=position_vector  +step +inv +proj=cart +ellps=bessel  +step +proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro
  103478.0275    244736.8250      543.7213           inf


> We didn't find the bug-ticket by the given link http://bugzilla.remotesensing.org/show_bug.cgi?id=194  Can you share the bug ticket to understand the code change?

I believe it has been completely lost. Anyway this was so looong ago and this code has been entirely rewritten since.

**Comment by busstoptaktik** [comment] 2022-04-22 19:24
@sgamperl have you tried roundtripping your computation? I believe PROJ roundtrips to within some reasonable factor considering floating point roundoff. It may be slightly more roundtrippingly correct if taking the EPSG approach, as referred to by @rouault above.

You state that your expected results are "correct", but by which authority is this correctness guaranteed? Apparently, if I interpret your words correctly, by reference to opaque closed source software. As @rouault explains above it is pretty hard to reproduce your results in a roundtrip-symmetric way, so please try roundtripping through the software, you expect to work correctly, and post the results here

**Comment by sgamperl** [comment] 2022-04-25 13:13
Thanks for your feedback to this issue.

We investigated our local transformation parameter and found that the parameters are for the transformation from ETRS89 to MGI (BESSEL elliposid). To use this in the PROJ string with the +towgs84 switch we have to calculate them from MGI TO ETRS89. I think this is the reason that we didn't get the expected results.

I will test the new parameters and post the results here.

**Comment by busstoptaktik** [comment] 2022-05-06 07:16
> I will test the new parameters and post the results here.

@sgamperl any news on this? (if you do not have the time to follow up with your results, we can just close the issue, if you prefer)

**Comment by sgamperl** [comment] 2022-05-06 09:38
As mentioned our parameters come from a product which outputs the parameter for transforming points from ETRS89 to MGI

The parameters from ETRS89 to MGI are 
**1243.664,422.935,241.661,16.0070831140,-18.7400563071,3.2832620357,-48.8214**

We calculated the invers transformation parameter. The correct parameters for the +towgs84 switch (=MGI to ETRS89) are 
**1243.574593551425,422.9153848595346,241.79500839414985,16.007083920000003,-18.740056320000004,3.2832604800000005, -48.81901658737586**

They are slightly different from the above parameters. 

With the following transformation pipeline we now get the same results as in the other products (Leica, rmGEO).

$ echo "11.702111000658 47.333295771703 592.292" | cct -d 4 +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=1243.574593551425 +y=422.9153848595346 +z=241.79500839414985 +rx=16.007083114 +ry=-18.7400563071 +rz=3.2832620357 +s=-48.81901658737586 +convention=position_vector +exact +step +inv +proj=cart +ellps=bessel +step +proj=tmerc +lat_0=0 +lon_0=28 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro

Expected destination coordinates: (103478.022, 244736.817, 543.64)
Calculated coordinates: (103478.0221, 244736.8172, 543.6397)

Now our results with the PROJ library are fine. There is no problem in the source code of the helmert transformation. You can close the ticket.

Thanks for helping here.

**Closed as completed** 2022-05-06 09:59 UTC
