### ISSUE TITLE
Transform X,Y,Z from source to dest with approximate Grid Shift

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/proj.4#4077] opened 2024-03-10 15:54 UTC
Is it possible to Transform X,Y,Z from source to dest with ignore Grid Shift but use an approximate Grid Shift.
one solution that I think of is egm96 that is cover all the world. is it can use as an approximate Z for all other
Vertical Grid Shifts ?

**Comment by hobu** [comment] 2024-03-10 15:58
@aharondavid if you keep opening tickets and for user questions like this that you can solve by spending time with the source code yourself you are going to get blocked.

A more fruitful path to success is to write a cogent, researched, and specific email to the [PROJ mailing list](https://proj.org/en/9.4/community/channels.html#mailing-list).

**Comment by rouault** [comment] 2024-03-10 15:58
this is actually a duplicate of https://github.com/OSGeo/PROJ/issues/1743

**Closed as completed by hobu** 2024-03-10 15:58 UTC
Labels: feature request

**Comment by aharondavid** [comment] 2024-03-10 16:10
> @aharondavid if you keep opening tickets and for user questions like this that you can solve by spending time with the source code yourself you are going to get blocked.
> 
> A more fruitful path to success is to write a cogent, researched, and specific email to the [PROJ mailing list](https://proj.org/en/9.4/community/channels.html#mailing-list).

OK
