### ISSUE TITLE
EPSG 6316 doesn't cover area of North Macedonia

### ISSUE THREAD

**Issue by bidrizi74** [OSGeo/proj.4#3247] opened 2022-07-02 19:02 UTC
Latest situation: 
In QGIS 3.26.0 version, , in list of Coordinate Reference Systems (CRS), CRS with code EPSG 6316 doesn't cover area of North Macedonia. With this, North Macedonian CRS based on EPSG 6316 parameters cannot be used in QGIS. Situation should be same in all software which use proj and epsg databases for CRS’s. 
This probably is because of two zones that cover EPSG 6316 (https://epsg.org/crs_6316/MGI-1901-Balkans-zone-7.html?sessionkey=z3r4rmfri7), one for other exYugoslavia countries (EPSG 1711) and second one for North Macedonia (EPSG 1148). This can be practicaly recogized if you add data in other CRS than WGS84 and if you use "Ask for datum transformation if several are available" option in "Settings/Options/Coordinate transformation and operations". In that case if you use EPSG 6316, all datum transformations will be available except datum transformation for North Macedonian territory which should be done by using EPSG 6206 as default datum transformation.
This issue can be solved only in a case to give other-separate EPSG code for North Macedonia with the second extend (EPSG 1148, extend of national area) of EPSG 6316, or to define sub-code of EPSG 6316 for second extend 1148, that should be linked to 6206 as default datum transformation for this area.

Example of projstring for North Macedonian area:
+proj=tmerc +lat_0=0 +lon_0=21 +k=0.9999 +x_0=7500000 +y_0=0 +ellps=bessel +towgs84=521.748,229.489,590.921,4.029,4.488,-15.521,-9.78 +units=m +no_defs

In a case of any missunderstanding, please get in touch me via email [bashkim.idrizi@yahoo.com](mailto:bashkim.idrizi@yahoo.com) any time.

**Comment by rouault** [comment] 2022-07-02 19:22
duplicate of #3246

**Closed as completed by rouault** 2022-07-02 19:22 UTC
Labels: bug
