### ISSUE TITLE
Extend of North Macedonia (EPSG 1148) is exluded from EPSG6316 current version of QGIS 3.26! 

### ISSUE THREAD

**Issue by bidrizi74** [OSGeo/proj.4#3269] opened 2022-07-25 17:20 UTC
In QGIS V 3.26.1, same as it was on QGIS V3.26.0 version, situation is same. There is no change in CRS for North Macedonia. 
   
In EPSG codes, CRS with EPSG 6316 (https://epsg.org/crs_6316/MGI-1901-Balkans-zone-7.html?sessionkey=poxbm3et26) has 2 extends, 1 (one) for 7th balkan zone (EPSG 1711 code for extend) and another for North Macedonia (EPSG 1148 code for zone extend). 
![image](https://user-images.githubusercontent.com/79769916/180670076-29b825d8-6f9f-49ac-8288-7fed9c55667a.png)
   
In QGIS 3.26.1 version,  when using EPSG 6316, software by default use first zone from EPSG registry database (7th balkan zone with EPSG 1711 code for extend), while second zone that belongs to North Macedonian area (EPSG 1148 code for zone extend) is totaly excluded from QGIS. 
![image](https://user-images.githubusercontent.com/79769916/180670301-5fada4c7-bffa-4235-8313-9eff893e3c66.png)
   
Main aim of separating zone of North Macedonia from general 7th balkan zone (EPSG 1711) is to establish sepparate CRS for North Macedonia, which later via Proj to be linked to default datum transformation parameters, in a same way as EPSG 6204 and 9945, sinse in North Macedonia official geospatial data are available in three CRS's (6316, 6204 and 9945). This is the reason why all three CRSs' should be defined correctly with all parameters. 
EPSG 6204 and 9945 and correctly defined and their ussage is perfect. Now problem with 6316 for North Macedonia have to be solved!  
![image](https://user-images.githubusercontent.com/79769916/180670445-c69079a1-de5c-450a-a245-960e1ef1ada4.png)
![image](https://user-images.githubusercontent.com/79769916/180670813-bc590867-e7d8-4769-a677-7a38eb9ebe28.png)

Best way to reproduce this issue is to create sepparate CRS for North Macedonian area with second extend (EPSG 1148) of EPSG 6316, which will be use default datum transformation EPSG 6206 from MGI 1901 to WGS 84, or to define subcode of EPSG 6316 for the area of North Macedonia with extend 1148, which should be linked to EPSG 6206 for datum transformation, as previously EPSG 6204 and EPSG 9945 are linked to EPSG 6206 for datum trasformation (Example of projstring: +proj=tmerc +lat_0=0 +lon_0=21 +k=0.9999 +x_0=7500000 +y_0=0 +ellps=bessel +towgs84=521.748,229.489,590.921,4.029,4.488,-15.521,-9.78 +units=m +no_defs). 

This issue is reported previously for QGIS 3.26.0 version also https://github.com/OSGeo/PROJ/issues/3246! 

For any further questions, please don't hesitate to write me. 
Best regards, 
Bashkim.

**Comment by nyalldawson** [comment] 2022-07-25 18:47
Duplicate of https://github.com/OSGeo/PROJ/issues/3246 -- (please don't file new tickets for the same issue)

**Closed as completed** 2022-07-30 16:21 UTC
Labels: bug
