### ISSUE TITLE
Offer Offline HTML documentation download

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3807] opened 2023-07-03 13:14 UTC
In 
https://github.com/GenericMappingTools/gmt/issues/7597 we see Proj doesn't have a HTML Offline document set. Only PDF...

We also see a way of mentioning a wget way users could use to get an HTML set.

Maybe the Proj website should also mention such a method. Linux distributions can't always be counted on to include one. And the user might in fact not even have any distribution installed, and just want the HTML documents.

**Comment by mwtoews** [comment] 2023-07-04 10:53
Duplicate of #3808

**Closed as not planned by mwtoews** 2023-07-04 10:53 UTC
