### ISSUE TITLE
testprojinfo & proj_test_cpp_api time out with proj-7.2.1 since sqlite-3.39.0

### ISSUE THREAD

**Issue by vcunat** [OSGeo/proj.4#3254] opened 2022-07-07 19:10 UTC
I don't know if you intend to provide any kind of support for such combination, so feel free to close if not, etc.  In [distro](https://nixos.org) we still have some packages that use `proj-7.*` because their upstreams just didn't seem to work with newer versions.

```
The following tests FAILED:
         44 - testprojinfo (Timeout)
         51 - proj_test_cpp_api (Timeout)
Errors while running CTest
```
The issue is very well reproducible on different machines and different platforms, clearly bisected updating sqlite to 3.39.0.

_I first thought I were hitting #3077 but the sqlite version is different and `proj-9.0.0` seems unaffected._

**Comment by rouault** [comment] 2022-07-07 19:26
I cannot reproduce with PROJ master and sqlite 3.39.0.
Some time ago (can't recall when), I had to simplify some complex SQLite queries that were slow with some SQLite versions. I suspect this was past PROJ 7.
Closing as we only support the latest stable PROJ release.

**Closed as completed by rouault** 2022-07-07 19:26 UTC
Labels: bug

**Comment by vcunat** [comment] 2022-07-07 19:28
Well yes, I posted it's broken with proj 7 and OK with proj 9.  Thanks for fast clarification about the supported versions.
