### ISSUE TITLE
Minimum CMake version?

### ISSUE THREAD

**Issue by urschrei** [OSGeo/proj.4#3220] opened 2022-06-03 15:29 UTC
We'd like to list a minimum CMake version requirement in https://github.com/georust/proj, but I couldn't find a minimum version in the docs, and I had a build failure earlier using CMake 3.12.x (resolved by updating to 3.23.2).

**Comment by rouault** [comment] 2022-06-03 15:32
it's supposed to be 3.9: https://github.com/OSGeo/PROJ/blob/master/CMakeLists.txt#L12

can you paste the failure you got with 3.12 (and the exact CMake version) ?

**Comment by urschrei** [comment] 2022-06-03 15:34
I upgraded to 3.23.2 after I googled the error, which was related to 

`list sub-command REMOVE_ITEM requires two or more arguments.`

Let me see if I can downgrade and reproduce it.

**Comment by rouault** [comment] 2022-06-03 15:38
ah this is probably a duplicate of https://github.com/OSGeo/PROJ/pull/3087 that affected the 9.0 release. It will be fixed in 9.0.1

**Comment by rouault** [comment] 2022-06-03 15:39
closing as a duplicate of https://github.com/OSGeo/PROJ/issues/3083 actually.

**Closed as completed by rouault** 2022-06-03 15:39 UTC

**Comment by urschrei** [comment] 2022-06-03 15:40
Ah, that looks like it. Thanks!
